//获得二级目录
export const GET_TWO_CATALOG = 'GET_TWO_CATALOG'

export const GET_THREE_CATALOG = 'GET_THREE_CATALOG'

export const NAV_LIST_DATA = 'NAV_LIST_DATA'

export const LEFT_BAR_TOGGLE = 'LEFT_BAR_TOGGLE'